# -*- coding: utf-8 -*-
"""Show.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1luRWtNFexP77uMnn7RkVnBfHjsCSzsHy
"""

import os
import pandas as pd
import re
from TSB_UAD.core import tsb_uad
import matplotlib.pyplot as plt

def visualize_data(directory, filename):
    file_path = os.path.join(directory, filename)
    df = pd.read_csv(file_path, header=None)
    data = df[0].astype(float)
    labels = df[1]

    plt.figure(figsize=(24, 6))
    plt.plot(data, label='Time Series Data', linewidth=1)
    plt.scatter(df.index[labels == 1], data[labels == 1], color='red', label='Anomaly Points', s=50)
    plt.title(f'Time Series Visualization - {filename}')
    plt.xlabel('Time')
    plt.ylabel('Value')
    plt.legend()
    plt.show()

def visualize_all_files(directory):
    files = [f for f in os.listdir(directory) if f.endswith('.out')]

    # 정규 표현식을 사용하여 파일명에서 숫자 부분만 추출
    def extract_number(filename):
        match = re.search(r'\d+', filename)
        return int(match.group()) if match else float('inf')  # 숫자가 없는 경우는 리스트의 끝에 위치하도록 함

    files.sort(key=extract_number)  # 숫자 기준으로 정렬

    for file in files:
        visualize_data(directory, file)